### ISSUE TITLE
Q4 Community Building Sprint 1

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#11]
# Sprint 1: Strengthen the technical infrastructure

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/3279
- [ ] https://github.com/2i2c-org/community-showcase/issues/16
- [ ] https://github.com/2i2c-org/community-showcase/issues/17
- [ ] https://github.com/2i2c-org/community-showcase/issues/18
- [ ] https://github.com/2i2c-org/community-showcase/issues/19
- [ ] https://github.com/2i2c-org/community-showcase/issues/20
```

**Comment by jmunroe** [comment]
There are some partially completed tasks here. Moving them into later sprint so that I can close this sprint.
