### ISSUE TITLE
Q4 Community Building Sprint 3

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#13]
# Sprint 3

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/3279
- [ ] https://github.com/2i2c-org/community-showcase/issues/22
- [ ] https://github.com/2i2c-org/community-showcase/issues/23
- [ ] https://github.com/2i2c-org/community-showcase/issues/24
- [ ] https://github.com/2i2c-org/community-showcase/issues/20
- [ ] https://github.com/2i2c-org/community-showcase/issues/21
- [ ] https://github.com/2i2c-org/community-showcase/issues/25
```

**Comment by jmunroe** [comment]
Closing and transferring uncompleted work to https://github.com/2i2c-org/community-showcase/issues/10
