### ISSUE TITLE
Q4 Community Building Sprint 4

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#14]
# Sprint 4: Content theme: Building a open science communities with a hub

```[tasklist]
### Tasks
- [ ] sharing workflows between users and publishing to the world using JupyterBook
- [ ] document best practices for hub champions to control cloud costs
- [ ] create year end reports showing all of our communities have used there hubs (users + usage)
- [ ] iterate on communication best-practices for communication with our hub champions
- [ ] deliver second community demo 'Advanced Hub Management'
```

**Comment by jmunroe** [comment]
Closing and transferring uncompleted work to https://github.com/2i2c-org/community-showcase/issues/10
